// <auto-generated />
namespace BloodConnector.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class MakeTypeInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeTypeInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201711010351409_MakeTypeInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
