using BloodConnector.WebAPI.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace BloodConnector.WebAPI.Migrations
{
    using System.Data.Entity.Migrations;

    internal sealed class Configuration : DbMigrationsConfiguration<Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.
            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.

            context.Roles.AddOrUpdate(
                new IdentityRole { Id = "1", Name = "SuperAdmin"},
                new IdentityRole { Id = "2", Name = "Admin" },
                new IdentityRole { Id = "3", Name = "User" }
             );

            context.BloodGroup.AddOrUpdate(
                new BloodGroup { ID = 1, Symbole = "O-" },
                new BloodGroup { ID = 2, Symbole = "O+" },
                new BloodGroup { ID = 3, Symbole = "A-" },
                new BloodGroup { ID = 4, Symbole = "A+" },
                new BloodGroup { ID = 5, Symbole = "B-" },
                new BloodGroup { ID = 6, Symbole = "B+" },
                new BloodGroup { ID = 7, Symbole = "AB-" },
                new BloodGroup { ID = 8, Symbole = "AB+" }
            );

            context.Country.AddOrUpdate(
                new Country { ID = 2, Name = "Albania", TowLetterCode = "AL", PhonePrefix = 355 },
                new Country { ID = 3, Name = "Algeria", TowLetterCode = "DZ", PhonePrefix = 213 },
                new Country { ID = 4, Name = "Andorra", TowLetterCode = "AD", PhonePrefix = 376 },
                new Country { ID = 5, Name = "Angola", TowLetterCode = "AO", PhonePrefix = 244 },
                new Country { ID = 6, Name = "Argentina", TowLetterCode = "AR", PhonePrefix = 54 },
                new Country { ID = 7, Name = "Aruba", TowLetterCode = "AW", PhonePrefix = 297 },
                new Country { ID = 8, Name = "Australia", TowLetterCode = "AU", PhonePrefix = 61 },
                new Country { ID = 9, Name = "Bahamas", TowLetterCode = "BS", PhonePrefix = 1242 },
                new Country { ID = 10, Name = "Bahrain", TowLetterCode = "BH", PhonePrefix = 973 },
                new Country { ID = 11, Name = "Bangladesh", TowLetterCode = "BD", PhonePrefix = 880 },
                new Country { ID = 12, Name = "Belgium", TowLetterCode = "BE", PhonePrefix = 32 },
                new Country { ID = 13, Name = "Belize", TowLetterCode = "BZ", PhonePrefix = 501 },
                new Country { ID = 14, Name = "Benin", TowLetterCode = "BJ", PhonePrefix = 229 },
                new Country { ID = 15, Name = "Bhutan", TowLetterCode = "BT", PhonePrefix = 975 },
                new Country { ID = 16, Name = "Bolivia", TowLetterCode = "BO", PhonePrefix = 591 },
                new Country { ID = 17, Name = "Botswana", TowLetterCode = "BW", PhonePrefix = 267 },
                new Country { ID = 18, Name = "Brunei", TowLetterCode = "BN", PhonePrefix = 673 },
                new Country { ID = 19, Name = "Bulgaria", TowLetterCode = "BG", PhonePrefix = 359 },
                new Country { ID = 20, Name = "Burkina Faso", TowLetterCode = "BF", PhonePrefix = 226 },
                new Country { ID = 21, Name = "Canada", TowLetterCode = "CA", PhonePrefix = 1 },
                new Country { ID = 22, Name = "Colombia", TowLetterCode = "CO", PhonePrefix = 57 },
                new Country { ID = 23, Name = "Costa Rica", TowLetterCode = "CR", PhonePrefix = 506 },
                new Country { ID = 24, Name = "Cuba", TowLetterCode = "CU", PhonePrefix = 53 },
                new Country { ID = 25, Name = "Denmark", TowLetterCode = "DK", PhonePrefix = 45 },
                new Country { ID = 26, Name = "Djibouti", TowLetterCode = "DJ", PhonePrefix = 253 },
                new Country { ID = 27, Name = "Dominica", TowLetterCode = "DM", PhonePrefix = 1767 },
                new Country { ID = 28, Name = "Ecuador", TowLetterCode = "EC", PhonePrefix = 593 },
                new Country { ID = 29, Name = "Egypt", TowLetterCode = "EG", PhonePrefix = 20 },
                new Country { ID = 30, Name = "El Salvador", TowLetterCode = "SV", PhonePrefix = 503 },
                new Country { ID = 31, Name = "Eritrea", TowLetterCode = "ER", PhonePrefix = 291 },
                new Country { ID = 32, Name = "Estonia", TowLetterCode = "EE", PhonePrefix = 372 },
                new Country { ID = 33, Name = "Etiopia", TowLetterCode = "ET", PhonePrefix = 251 },
                new Country { ID = 34, Name = "Fiji", TowLetterCode = "FJ", PhonePrefix = 679 },
                new Country { ID = 35, Name = "Philippines", TowLetterCode = "PH", PhonePrefix = 63 },
                new Country { ID = 36, Name = "United Arab. Emirates", TowLetterCode = "AE", PhonePrefix = 971 },
                new Country { ID = 37, Name = "French Guyana", TowLetterCode = "GF", PhonePrefix = 594 },
                new Country { ID = 38, Name = "Gambia", TowLetterCode = "GM", PhonePrefix = 220 },
                new Country { ID = 39, Name = "Georgia", TowLetterCode = "GE", PhonePrefix = 995 },
                new Country { ID = 40, Name = "Gibraltar", TowLetterCode = "GI", PhonePrefix = 350 },
                new Country { ID = 41, Name = "Greenland", TowLetterCode = "GL", PhonePrefix = 299 },
                new Country { ID = 42, Name = "Guadelope", TowLetterCode = "GP", PhonePrefix = 590 },
                new Country { ID = 43, Name = "Guam", TowLetterCode = "GU", PhonePrefix = 1671 },
                new Country { ID = 44, Name = "Guinea", TowLetterCode = "GN", PhonePrefix = 224 },
                new Country { ID = 45, Name = "Guinea Bissau", TowLetterCode = "GW", PhonePrefix = 245 },
                new Country { ID = 46, Name = "Haiti", TowLetterCode = "HT", PhonePrefix = 509 },
                new Country { ID = 48, Name = "Greece", TowLetterCode = "GR", PhonePrefix = 30 },
                new Country { ID = 49, Name = "India", TowLetterCode = "IN", PhonePrefix = 91 },
                new Country { ID = 50, Name = "Indonesia", TowLetterCode = "ID", PhonePrefix = 62 },
                new Country { ID = 51, Name = "Iraq", TowLetterCode = "IQ", PhonePrefix = 964 },
                new Country { ID = 52, Name = "Iran", TowLetterCode = "IR", PhonePrefix = 98 },
                new Country { ID = 53, Name = "Ireland", TowLetterCode = "IE", PhonePrefix = 353 },
                new Country { ID = 54, Name = "Israel", TowLetterCode = "IL", PhonePrefix = 972 },
                new Country { ID = 55, Name = "Italy", TowLetterCode = "IT", PhonePrefix = 39 },
                new Country { ID = 56, Name = "Jamaica", TowLetterCode = "JM", PhonePrefix = 1876 },
                new Country { ID = 58, Name = "Cambodia", TowLetterCode = "KH", PhonePrefix = 855 },
                new Country { ID = 59, Name = "The Cap Verde-islands", TowLetterCode = "CV", PhonePrefix = 238 },
                new Country { ID = 60, Name = "Kenya", TowLetterCode = "KE", PhonePrefix = 254 },
                new Country { ID = 61, Name = "China", TowLetterCode = "CN", PhonePrefix = 86 },
                new Country { ID = 62, Name = "Kyrgyzstan", TowLetterCode = "KG", PhonePrefix = 996 },
                new Country { ID = 63, Name = "Congo", TowLetterCode = "CG", PhonePrefix = 242 },
                new Country { ID = 64, Name = "Korea, North", TowLetterCode = "KP", PhonePrefix = 850 },
                new Country { ID = 65, Name = "Croatia", TowLetterCode = "HR", PhonePrefix = 385 },
                new Country { ID = 66, Name = "Kuwait", TowLetterCode = "KW", PhonePrefix = 965 },
                new Country { ID = 67, Name = "Cyprus", TowLetterCode = "CY", PhonePrefix = 357 },
                new Country { ID = 68, Name = "Laos", TowLetterCode = "LA", PhonePrefix = 856 },
                new Country { ID = 69, Name = "Lesotho", TowLetterCode = "LS", PhonePrefix = 266 },
                new Country { ID = 70, Name = "Libya", TowLetterCode = "LY", PhonePrefix = 218 },
                new Country { ID = 71, Name = "Liechtenstein", TowLetterCode = "LI", PhonePrefix = 423 },
                new Country { ID = 72, Name = "Luxembourg", TowLetterCode = "LU", PhonePrefix = 352 },
                new Country { ID = 73, Name = "Macau", TowLetterCode = "MO", PhonePrefix = 853 },
                new Country { ID = 74, Name = "Macedonia", TowLetterCode = "MK", PhonePrefix = 389 },
                new Country { ID = 75, Name = "Malaysia", TowLetterCode = "MY", PhonePrefix = 60 },
                new Country { ID = 76, Name = "Mali", TowLetterCode = "ML", PhonePrefix = 223 },
                new Country { ID = 77, Name = "Malta", TowLetterCode = "MT", PhonePrefix = 356 },
                new Country { ID = 78, Name = "Morocco", TowLetterCode = "MA", PhonePrefix = 212 },
                new Country { ID = 79, Name = "Martinique", TowLetterCode = "MQ", PhonePrefix = 596 },
                new Country { ID = 80, Name = "Mauritius", TowLetterCode = "MU", PhonePrefix = 230 },
                new Country { ID = 81, Name = "Micronesia", TowLetterCode = "FM", PhonePrefix = 691 },
                new Country { ID = 82, Name = "Moldova", TowLetterCode = "MD", PhonePrefix = 373 },
                new Country { ID = 83, Name = "Mongolia", TowLetterCode = "MN", PhonePrefix = 976 },
                new Country { ID = 84, Name = "Namibia", TowLetterCode = "NA", PhonePrefix = 264 },
                new Country { ID = 85, Name = "The Netherlands", TowLetterCode = "NL", PhonePrefix = 31 },
                new Country { ID = 86, Name = "New Zealand", TowLetterCode = "NZ", PhonePrefix = 64 },
                new Country { ID = 87, Name = "Nigeria", TowLetterCode = "NG", PhonePrefix = 234 },
                new Country { ID = 88, Name = "Peru", TowLetterCode = "PE", PhonePrefix = 51 },
                new Country { ID = 89, Name = "Poland", TowLetterCode = "PL", PhonePrefix = 48 },
                new Country { ID = 90, Name = "Qatar", TowLetterCode = "QA", PhonePrefix = 974 },
                new Country { ID = 91, Name = "Rwanda", TowLetterCode = "RW", PhonePrefix = 250 },
                new Country { ID = 92, Name = "Sao Tome & Princip", TowLetterCode = "ST", PhonePrefix = 239 },
                new Country { ID = 93, Name = "Slovakia", TowLetterCode = "SK", PhonePrefix = 421 },
                new Country { ID = 94, Name = "Slovenia", TowLetterCode = "SI", PhonePrefix = 386 },
                new Country { ID = 95, Name = "Somalia", TowLetterCode = "SO", PhonePrefix = 252 },
                new Country { ID = 96, Name = "Sudan", TowLetterCode = "SD", PhonePrefix = 249 },
                new Country { ID = 97, Name = "Surinam", TowLetterCode = "SR", PhonePrefix = 597 },
                new Country { ID = 98, Name = "Swaziland", TowLetterCode = "SZ", PhonePrefix = 268 },
                new Country { ID = 99, Name = "Tajikstan", TowLetterCode = "TJ", PhonePrefix = 992 },
                new Country { ID = 100, Name = "Tchad", TowLetterCode = "TD", PhonePrefix = 235 },
                new Country { ID = 101, Name = "Thailand", TowLetterCode = "TH", PhonePrefix = 66 },
                new Country { ID = 102, Name = "Togo", TowLetterCode = "TG", PhonePrefix = 228 },
                new Country { ID = 103, Name = "Tunisia", TowLetterCode = "TN", PhonePrefix = 216 },
                new Country { ID = 104, Name = "Germany", TowLetterCode = "DE", PhonePrefix = 49 },
                new Country { ID = 105, Name = "USA", TowLetterCode = "US", PhonePrefix = 1 },
                new Country { ID = 106, Name = "Uzbekistan", TowLetterCode = "UZ", PhonePrefix = 998 },
                new Country { ID = 107, Name = "Yemen", TowLetterCode = "YE", PhonePrefix = 967 },
                new Country { ID = 108, Name = "Austria", TowLetterCode = "AT", PhonePrefix = 43 },
                new Country { ID = 110, Name = "Nicaragua", TowLetterCode = "NI", PhonePrefix = 505 },
                new Country { ID = 111, Name = "Pakistan", TowLetterCode = "PK", PhonePrefix = 92 },
                new Country { ID = 112, Name = "Puerto Rico", TowLetterCode = "PR", PhonePrefix = 1 },
                new Country { ID = 113, Name = "Russia", TowLetterCode = "RU", PhonePrefix = 7 },
                new Country { ID = 114, Name = "San Marino", TowLetterCode = "SM", PhonePrefix = 378 },
                new Country { ID = 115, Name = "Saudi Arabia", TowLetterCode = "SA", PhonePrefix = 966 },
                new Country { ID = 116, Name = "The Central African Repub...", TowLetterCode = "CF", PhonePrefix = 236 },
                new Country { ID = 117, Name = "St. Lucia", TowLetterCode = "LC", PhonePrefix = 1758 },
                new Country { ID = 118, Name = "South Africa", TowLetterCode = "ZA", PhonePrefix = 27 },
                new Country { ID = 119, Name = "Tanzania", TowLetterCode = "TZ", PhonePrefix = 255 },
                new Country { ID = 120, Name = "Tonga", TowLetterCode = "TO", PhonePrefix = 676 },
                new Country { ID = 121, Name = "Trinidad & Tobago", TowLetterCode = "TT", PhonePrefix = 1868 },
                new Country { ID = 122, Name = "Turkey", TowLetterCode = "TR", PhonePrefix = 90 },
                new Country { ID = 123, Name = "Ukraina", TowLetterCode = "UA", PhonePrefix = 380 },
                new Country { ID = 124, Name = "Uruguay", TowLetterCode = "UY", PhonePrefix = 598 },
                new Country { ID = 125, Name = "Vanuatu", TowLetterCode = "VU", PhonePrefix = 678 },
                new Country { ID = 126, Name = "Vietnam", TowLetterCode = "VN", PhonePrefix = 84 },
                new Country { ID = 127, Name = "Zimbabwe", TowLetterCode = "ZW", PhonePrefix = 263 },
                new Country { ID = 128, Name = "Afghanistan", TowLetterCode = "AF", PhonePrefix = 93 },
                new Country { ID = 129, Name = "American Samoa", TowLetterCode = "AS", PhonePrefix = 1684 },
                new Country { ID = 130, Name = "Armenia", TowLetterCode = "AM", PhonePrefix = 374 },
                new Country { ID = 131, Name = "Azerbaijan", TowLetterCode = "AZ", PhonePrefix = 994 },
                new Country { ID = 132, Name = "Barbados", TowLetterCode = "BB", PhonePrefix = 1246 },
                new Country { ID = 133, Name = "Bermuda", TowLetterCode = "BM", PhonePrefix = 1441 },
                new Country { ID = 134, Name = "Bosnia-Hercegovina", TowLetterCode = "BA", PhonePrefix = 387 },
                new Country { ID = 135, Name = "Burundi", TowLetterCode = "BI", PhonePrefix = 257 },
                new Country { ID = 136, Name = "Chile", TowLetterCode = "CL", PhonePrefix = 56 },
                new Country { ID = 137, Name = "Cook islands", TowLetterCode = "CK", PhonePrefix = 682 },
                new Country { ID = 138, Name = "The Dominican Republic", TowLetterCode = "DO", PhonePrefix = 1809 },
                new Country { ID = 140, Name = "Finland", TowLetterCode = "FI", PhonePrefix = 358 },
                new Country { ID = 141, Name = "France", TowLetterCode = "FR", PhonePrefix = 33 },
                new Country { ID = 142, Name = "Gabon", TowLetterCode = "GA", PhonePrefix = 241 },
                new Country { ID = 143, Name = "Ghana", TowLetterCode = "GH", PhonePrefix = 233 },
                new Country { ID = 144, Name = "Grenada", TowLetterCode = "GD", PhonePrefix = 1473 },
                new Country { ID = 145, Name = "Guatemala", TowLetterCode = "GT", PhonePrefix = 502 },
                new Country { ID = 146, Name = "Guyana", TowLetterCode = "GY", PhonePrefix = 592 },
                new Country { ID = 147, Name = "Honduras", TowLetterCode = "HN", PhonePrefix = 504 },
                new Country { ID = 148, Name = "Iceland", TowLetterCode = "IS", PhonePrefix = 354 },
                new Country { ID = 149, Name = "Japan", TowLetterCode = "JP", PhonePrefix = 81 },
                new Country { ID = 150, Name = "Jordan", TowLetterCode = "JO", PhonePrefix = 962 },
                new Country { ID = 151, Name = "Cameroon", TowLetterCode = "CM", PhonePrefix = 237 },
                new Country { ID = 152, Name = "Kazakhstan", TowLetterCode = "KZ", PhonePrefix = 7 },
                new Country { ID = 154, Name = "Korea, South", TowLetterCode = "KR", PhonePrefix = 82 },
                new Country { ID = 155, Name = "Latvia", TowLetterCode = "LV", PhonePrefix = 371 },
                new Country { ID = 156, Name = "Liberia", TowLetterCode = "LR", PhonePrefix = 231 },
                new Country { ID = 157, Name = "Lithuania", TowLetterCode = "LT", PhonePrefix = 370 },
                new Country { ID = 158, Name = "Madagascar", TowLetterCode = "MG", PhonePrefix = 261 },
                new Country { ID = 159, Name = "Maldives", TowLetterCode = "MV", PhonePrefix = 960 },
                new Country { ID = 160, Name = "The Marshall Islands", TowLetterCode = "MH", PhonePrefix = 692 },
                new Country { ID = 161, Name = "Mexico", TowLetterCode = "MX", PhonePrefix = 52 },
                new Country { ID = 162, Name = "Monaco", TowLetterCode = "MC", PhonePrefix = 377 },
                new Country { ID = 163, Name = "Myanmar", TowLetterCode = "MM", PhonePrefix = 95 },
                new Country { ID = 164, Name = "Nepal", TowLetterCode = "NP", PhonePrefix = 977 },
                new Country { ID = 165, Name = "Niger", TowLetterCode = "NE", PhonePrefix = 227 },
                new Country { ID = 166, Name = "Panama", TowLetterCode = "PA", PhonePrefix = 507 },
                new Country { ID = 167, Name = "Portugal", TowLetterCode = "PT", PhonePrefix = 351 },
                new Country { ID = 168, Name = "Samoa", TowLetterCode = "WS", PhonePrefix = 685 },
                new Country { ID = 169, Name = "Senegal", TowLetterCode = "SN", PhonePrefix = 221 },
                new Country { ID = 170, Name = "Sierra Leone", TowLetterCode = "SL", PhonePrefix = 232 },
                new Country { ID = 171, Name = "Sri Lanka", TowLetterCode = "LK", PhonePrefix = 94 },
                new Country { ID = 172, Name = "Switzerland", TowLetterCode = "CH", PhonePrefix = 41 },
                new Country { ID = 173, Name = "Syria", TowLetterCode = "SY", PhonePrefix = 963 },
                new Country { ID = 174, Name = "Taiwan (Province og China)", TowLetterCode = "TW", PhonePrefix = 886 },
                new Country { ID = 175, Name = "Czech", TowLetterCode = "CZ", PhonePrefix = 420 },
                new Country { ID = 176, Name = "Tuvalu", TowLetterCode = "TV", PhonePrefix = 688 },
                new Country { ID = 177, Name = "Hungary", TowLetterCode = "HU", PhonePrefix = 36 },
                new Country { ID = 178, Name = "Venezuela", TowLetterCode = "VE", PhonePrefix = 58 },
                new Country { ID = 179, Name = "Norway", TowLetterCode = "NO", PhonePrefix = 47 },
                new Country { ID = 180, Name = "Antigua & Barbuda", TowLetterCode = "AG", PhonePrefix = 1268 },
                new Country { ID = 181, Name = "Brazil", TowLetterCode = "BR", PhonePrefix = 55 },
                new Country { ID = 182, Name = "The Cayman Islands", TowLetterCode = "KY", PhonePrefix = 1345 },
                new Country { ID = 183, Name = "Equatorial-Guinea", TowLetterCode = "GQ", PhonePrefix = 240 },
                new Country { ID = 184, Name = "French Polynesia", TowLetterCode = "PF", PhonePrefix = 689 },
                new Country { ID = 185, Name = "China (Hong Kong SAR)", TowLetterCode = "HK", PhonePrefix = 852 },
                new Country { ID = 186, Name = "The Virgin Islands", TowLetterCode = "VI", PhonePrefix = 1340 },
                new Country { ID = 187, Name = "Kiribati", TowLetterCode = "KI", PhonePrefix = 686 },
                new Country { ID = 188, Name = "Lebanon", TowLetterCode = "LB", PhonePrefix = 961 },
                new Country { ID = 189, Name = "Malawi", TowLetterCode = "MW", PhonePrefix = 265 },
                new Country { ID = 190, Name = "Mauritania", TowLetterCode = "MR", PhonePrefix = 222 },
                new Country { ID = 191, Name = "Nauru", TowLetterCode = "NR", PhonePrefix = 674 },
                new Country { ID = 192, Name = "Paraguay", TowLetterCode = "PY", PhonePrefix = 595 },
                new Country { ID = 193, Name = "The Seychell Islands", TowLetterCode = "SC", PhonePrefix = 248 },
                new Country { ID = 194, Name = "Sweden", TowLetterCode = "SE", PhonePrefix = 46 },
                new Country { ID = 195, Name = "Turkmenistan", TowLetterCode = "TM", PhonePrefix = 993 },
                new Country { ID = 196, Name = "The Faroe Islands", TowLetterCode = "FO", PhonePrefix = 298 },
                new Country { ID = 197, Name = "Mayotte", TowLetterCode = "YT", PhonePrefix = 269 },
                new Country { ID = 198, Name = "Mozambique", TowLetterCode = "MZ", PhonePrefix = 258 },
                new Country { ID = 199, Name = "OmaTowLetterCode = ", TowLetterCode = "OM", PhonePrefix = 968 },
                new Country { ID = 200, Name = "Roumania", TowLetterCode = "RO", PhonePrefix = 40 },
                new Country { ID = 201, Name = "Singapore", TowLetterCode = "SG", PhonePrefix = 65 },
                new Country { ID = 202, Name = "St. Vincent", TowLetterCode = "VC", PhonePrefix = 1784 },
                new Country { ID = 203, Name = "Uganda", TowLetterCode = "UG", PhonePrefix = 256 },
                new Country { ID = 204, Name = "Zambia", TowLetterCode = "ZM", PhonePrefix = 260 },
                new Country { ID = 205, Name = "Papua-Ny Guinea", TowLetterCode = "PG", PhonePrefix = 675 },
                new Country { ID = 206, Name = "Spain", TowLetterCode = "ES", PhonePrefix = 34 },
                new Country { ID = 207, Name = "Great Britain and Northern Ireland", TowLetterCode = "GB", PhonePrefix = 44 },
                new Country { ID = 208, Name = "Solomon Islands", TowLetterCode = "SB", PhonePrefix = 677 },
                new Country { ID = 209, Name = "Anguilla", TowLetterCode = "AI", PhonePrefix = 1264 },
                new Country { ID = 210, Name = "Antarctica", TowLetterCode = "AQ", PhonePrefix = 672 },
                new Country { ID = 213, Name = "Christmas Island", TowLetterCode = "CX", PhonePrefix = 61 },
                new Country { ID = 214, Name = "Cocos (Keeling) Islands", TowLetterCode = "CC", PhonePrefix = 61 },
                new Country { ID = 215, Name = "Congo, The Democratic Republic Of The", TowLetterCode = "CD", PhonePrefix = 243 },
                new Country { ID = 216, Name = "Falkland Islands (Malvinas)", TowLetterCode = "FK", PhonePrefix = 500 },
                new Country { ID = 220, Name = "Holy See (Vatican City State)", TowLetterCode = "VA", PhonePrefix = 39 },
                new Country { ID = 221, Name = "Isle Of Man", TowLetterCode = "IM", PhonePrefix = 44 },
                new Country { ID = 222, Name = "Jersey", TowLetterCode = "JE", PhonePrefix = 44 },
                new Country { ID = 235, Name = "Serbia", TowLetterCode = "RS", PhonePrefix = 381 },
                new Country { ID = 237, Name = "Svalbard And Jan Mayen", TowLetterCode = "SJ", PhonePrefix = 47 },
                new Country { ID = 245, Name = "Timor-Leste", TowLetterCode = "TL", PhonePrefix = 670 },
                new Country { ID = 246, Name = "Montenegro", TowLetterCode = "ME", PhonePrefix = 382 },
                new Country { ID = 247, Name = "Curaçao", TowLetterCode = "AN", PhonePrefix = 599 },
                new Country { ID = 248, Name = "New Caledonia", TowLetterCode = "NC", PhonePrefix = 687 },
                new Country { ID = 249, Name = "Occupied Palestinian Territory", TowLetterCode = "PS", PhonePrefix = 970 },
                new Country { ID = 250, Name = "Belarus", TowLetterCode = "BY", PhonePrefix = 375 },
                new Country { ID = 252, Name = "South Sudan", TowLetterCode = "SS", PhonePrefix = 211 },
                new Country { ID = 257, Name = "Bouvet Island", TowLetterCode = "BV", PhonePrefix = 0 },
                new Country { ID = 258, Name = "British Indian Ocean Territory", TowLetterCode = "IO", PhonePrefix = 0 },
                new Country { ID = 259, Name = "French Southern Territories", TowLetterCode = "TF", PhonePrefix = 0 },
                new Country { ID = 260, Name = "Guernsey", TowLetterCode = "GG", PhonePrefix = 0 },
                new Country { ID = 261, Name = "Heard Island And Mcdonald Islands", TowLetterCode = "HM", PhonePrefix = 0 },
                new Country { ID = 262, Name = "Montserrat", TowLetterCode = "MS", PhonePrefix = 0 },
                new Country { ID = 263, Name = "Niue", TowLetterCode = "NU", PhonePrefix = 0 },
                new Country { ID = 264, Name = "Norfolk Island", TowLetterCode = "NF", PhonePrefix = 0 },
                new Country { ID = 265, Name = "Northern Mariana Islands", TowLetterCode = "MP", PhonePrefix = 0 },
                new Country { ID = 266, Name = "Palau", TowLetterCode = "PW", PhonePrefix = 0 },
                new Country { ID = 267, Name = "Pitcairn", TowLetterCode = "PN", PhonePrefix = 0 },
                new Country { ID = 268, Name = "Réunion", TowLetterCode = "RE", PhonePrefix = 0 },
                new Country { ID = 269, Name = "Saint Barthélemy", TowLetterCode = "BL", PhonePrefix = 0 },
                new Country { ID = 270, Name = "Saint Helena", TowLetterCode = "SH", PhonePrefix = 0 },
                new Country { ID = 271, Name = "Saint Kitts And Nevis", TowLetterCode = "KN", PhonePrefix = 0 },
                new Country { ID = 272, Name = "Saint Martin (French part)", TowLetterCode = "MF", PhonePrefix = 0 },
                new Country { ID = 273, Name = "Saint Pierre And Miquelon", TowLetterCode = "PM", PhonePrefix = 0 },
                new Country { ID = 274, Name = "South Georgia And The South Sandwich Islands", TowLetterCode = "GS", PhonePrefix = 0 },
                new Country { ID = 275, Name = "Tokelau", TowLetterCode = "TK", PhonePrefix = 0 },
                new Country { ID = 276, Name = "Turks And Caicos Islands", TowLetterCode = "TC", PhonePrefix = 0 },
                new Country { ID = 277, Name = "United States Minor Outlying Islands", TowLetterCode = "UM", PhonePrefix = 0 },
                new Country { ID = 278, Name = "Virgin Islands, British", TowLetterCode = "VG", PhonePrefix = 0 },
                new Country { ID = 279, Name = "Wallis And Futuna", TowLetterCode = "WF", PhonePrefix = 0 },
                new Country { ID = 280, Name = "Western Sahara", TowLetterCode = "EH", PhonePrefix = 0 },
                new Country { ID = 281, Name = "Åland Islands", TowLetterCode = "AX", PhonePrefix = 0}
            );

            base.Seed(context);
        }
    }
}
